
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dixdeoaqjjhqxwvemcyu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpeGRlb2FxampocXh3dmVtY3l1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0ODUzMDQsImV4cCI6MjA2MzA2MTMwNH0.wqP-2lfE_mkq4oZdUe7q2UENug6HSuj7jrwBWnd7e70";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
